### ISSUE TITLE
[Docs] Change <a> tag settings in the docs to not open a new page when clicking on it

### ISSUE THREAD

**Issue by Luna-Klatzer** [Kipper-Lang/Kipper#319]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current State & Issue

When using the documentation, the links added to the page content always open a new tab instead of redirecting the current page to the selected URL, which can be annoying and unnecessary.

### Expected Changes & Improvements

Change build settings for the Markdown of the docs.

### Referenced sites

- The docs as a whole (https://luna-klatzer.github.io/Kipper/docs/)

**Comment by lorenzholzbauer** [comment]
Working on it

**Comment by Luna-Klatzer** [comment]
Fixed with #321
