### ISSUE TITLE
[Feature] Add ternary conditional operator

### ISSUE THREAD

**Issue by ByteWolf-dev** [Kipper-Lang/Kipper#534]
### Is there an existing proposal for this?

- [X] I have searched the existing issues

### This feature does not exist in the latest version

- [X] I am using the latest version

### Proposal

Add the ternary conditional operator

`condition ? expressionIfTrue : expressionIfFalse;`

For example:

```ts
let checkNumber = (num) => num > 0 ? 'Positive' : 'Negative or Zero';
console.log(checkNumber(5));  // Output: 'Positive'
console.log(checkNumber(-3)); // Output: 'Negative or Zero'
```

### Exact behaviour / changes you want

- [x] Add ternary operator syntax.
- [x] Add semantic analysis and type checking for the AST Node.
- [x] Add translation to JavaScript and Typescript.

**Comment by Luna-Klatzer** [comment]
Implemented by #565
