### ISSUE TITLE
[Feature] Add runtime type generation for builtin types

### ISSUE THREAD

**Issue by lorenzholzbauer** [Kipper-Lang/Kipper#659]
### Is there an existing proposal for this?

- [X] I have searched the existing issues

### This feature does not exist in the latest version

- [X] I am using the latest version

### Proposal

```js
class Type {
    constructor(name, fields, methods, baseType = null) {
        this.name = name;
        this.fields = fields;
        this.methods = methods;
        this.baseType = baseType;
    }
}
```

### Exact behaviour / changes you want

- [ ] Implement a runtime type system for built-in types.

**Comment by Luna-Klatzer** [comment]
Implemented as part of #688.
