### ISSUE TITLE
[Feature] Implement classes with class properties and class methods

### ISSUE THREAD

**Issue by ByteWolf-dev** [Kipper-Lang/Kipper#665]
### Is there an existing proposal for this?

- [X] I have searched the existing issues

### This feature does not exist in the latest version

- [X] I am using the latest version

### Proposal

Implement AST Nodes, semantic analysis and code generation for classes, class-methods and class-properties

### Exact behaviour / changes you want

The compiler should be able to create classes which can have methods and/or properties.

**Comment by Luna-Klatzer** [comment]
Implemented by #675.
