### ISSUE TITLE
[Feature] Implement `new` to be able to instantiate objects

### ISSUE THREAD

**Issue by ByteWolf-dev** [Kipper-Lang/Kipper#679]
### Is there an existing proposal for this?

- [X] I have searched the existing issues

### This feature does not exist in the latest version

- [X] I am using the latest version

### Proposal

We want to implement the `new` keyword so that objects can be instantiated.

### Exact behaviour / changes you want

Here is an example:

```js
class Person {
    name: str;

    constructor(name: str) {
        this.name = name;
    }
}

// Instantiate the class
const person = new Person("Alice", 30);```

**Comment by Luna-Klatzer** [comment]
Implemented by #689
